export const endpoint = '/api';

export const actionTypes = {
  FETCH_COCKTAILS: 'MODELS/COCKTAILS/FETCH_COCKTAILS',
  FETCH_COCKTAILS_SUCCESS: 'MODELS/COCKTAILS/FETCH_COCKTAILS_SUCCESS',
  FETCH_COCKTAILS_ERROR: 'MODELS/COCKTAILS/FETCH_COCKTAILS_ERROR',
};
