export const endpoint = '/api';

export const actionTypes = {
  EMIT_FETCH_COCKTAILS_FINISH: 'MODELS/COCKTAILS/EMIT/FETCH_COCKTAILS_FINISH',
  FETCH_COCKTAILS: 'MODELS/COCKTAILS/FETCH_COCKTAILS',
  FETCH_COCKTAILS_SUCCESS: 'MODELS/COCKTAILS/FETCH_COCKTAILS_SUCCESS',
};
