export const endpoint = 'http://localhost:8080/api/';

export const actionTypes = {
  EMIT_FETCH_DOGS_RECIPES_FINISH: 'MODELS/DOGS_RECIPES/EMIT/FETCH_DOGS_RECIPES_FINISH',
  FETCH_DOGS_RECIPES: 'MODELS/DOGS_RECIPES/FETCH_DOGS_RECIPES',
  FETCH_DOGS_RECIPES_SUCCESS: 'MODELS/DOGS_RECIPES/FETCH_DOGS_RECIPES_SUCCESS',
};
